# -*- coding: utf-8 -*-
"""TUGAS ALGORITMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCIrG8Vui_Zn0_aiSSQAXyxwx_DfYIo2
"""

# Kalkulator Sederhana

def tambah(a, b):
    return a + b
'''MENJUMLAHKAN DUA ANGKA YANG DIMASUKKAN'''

def kurang(a, b):
    return a - b
'''MENGURANGI ANGKA PERTAMA DAN KEDUA'''

def kali(a, b):
    return a * b
'''MENGALIKAN DUA ANGKA YANG DIMASUKKAN'''

def bagi(a, b):
    if b == 0:
        return "Tidak bisa dibagi dengan nol"
    return a / b
'''MEMBAGI ANGKA PERTAMA DENGAN KEDUA TAPI KALAU PEMBAGINYA NOL PROGRAM
AKAN MENGEMBAIKAN PESAN ERROR KARNA TIDAK BISA DIBAGI NOL'''

def menu():
    print("=== Kalkulator Sederhana ===")
    print("1. Tambah")
    print("2. Kurang")
    print("3. Kali")
    print("4. Bagi")
    print("5. Keluar")
    '''MENAMPILKAN PILIHAN SUPAYA PENGGUNA TAHU MENGGUNAKAN ANGKA BERAPA'''

while True:
  '''MEMBUAT PROGRAM JALAN TERUS SAMPAI PENGGUNA MEMILIH OPSI KELUAR'''

    menu()
    pilihan = input("Pilih operasi (1-5): ")
'''MEMINTA PENGGUNA MEMILIH OPERASI YANG AKAN DILAKUKAN DARI MENU YANG
DITAMPILKAN SEBELUMNYA'''

    if pilihan == "5":
        print("Terima kasih telah menggunakan kalkulator.")
        break
        '''APABILA PENGGUNA MEMASUKKAN ANGKA 5 MAKA PROGRAM AKAN BERHENTI'''

    angka1 = float(input("Masukkan angka pertama: "))
    angka2 = float(input("Masukkan angka kedua: "))
    '''PROGRAM MINTA MASUKIN DUA ANGKA DAN DI UBAH KEBENTUK DESIMAL'''

    if pilihan == "1":
        print("Hasil:", tambah(angka1, angka2))
        '''KALAU PILIH 1 MAKA ANGKA TAMBAH AKAN DIJALANKAN'''

    elif pilihan == "2":
        print("Hasil:", kurang(angka1, angka2))
        '''KALAU PILIH 2 MAKA ANGKA KURANG AKAN DIJALANKAN'''

    elif pilihan == "3":
        print("Hasil:", kali(angka1, angka2))
        '''KALAU PILIH 3 MAKA ANGKA KALI AKAN DIJALANKAN'''

    elif pilihan == "4":
        print("Hasil:", bagi(angka1, angka2))
        '''KALAU PILIH 4 MAKA ANGKA BAGI AKAN DIJALANKAN'''

    else:
        print("Pilihan tidak valid.")
        '''KALAU MASUKIN ANGKA SELAIN 1-5 PROGRAM AKAN MENGEMBAIKAN
        PESAN ERROR'''